language: generic
sudo: required
dist: trusty

-before_install:
  - sudo apt-get -qq -y update

install:
  - sudo add-apt-repository -y ppa:ostogvin/tjo-develop
  - sudo apt-get update
  - sudo apt-get install build-essential liblua5.1-0 liblua5.1-0-dev libprotobuf-dev libsqlite3-dev protobuf-compiler shapelib libshp-dev libboost1.58-all-dev

script:
  - make
  - make install
